# 1. Base image
FROM python:3.11-slim
# 2. Set working directory
WORKDIR /app
# 3. Copy dependency file
COPY requirements.txt .
# 4. Install dependenciesR
RUN pip install --no-cache-dir -r requirements.txt
# 5. Copy application code
COPY . .
# 6. Expose port
EXPOSE 5000
# 7. Run the app
CMD ["python", "app.py"]